In [12]:
import numpy as np
import pandas as pd

In [ ]:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [ ]:
Ans:- yes, there is a difference in the data type of variables list_ and array_list. "list_" is a python
    list object, while 'array_list' is a  Numpy ndarray object.
    
    The elements of list are 'strings' whereas the element of array_list is 'integer' .Here's the code:

In [13]:
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

In [14]:
list_

['1', '2', '3', '4', '5']

In [16]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [24]:
type(list_)

list

In [25]:
type(array_list)

numpy.ndarray

In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [26]:
array_list = np.array(object = list_, dtype = int)


In [27]:
array_list

array([1, 2, 3, 4, 5])

In [28]:
type(list_)

list

In [29]:
type(array_list)

numpy.ndarray

In [31]:
array_list.dtype


dtype('int32')

In [ ]:
Yes, there is a difference in the data types of the elements present in both variables 'list_' and 'array_list'.
when 'array_list' is created with 'dtype= int' , Numpy will convert the string values in 'list_' to integer values when 
creating the array

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [32]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [33]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [34]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
num_array.shape

(2, 3)

In [37]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [45]:
zeros = np.zeros((3,3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
zeros.size

9

In [48]:
zeros.shape

(3, 3)

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [52]:
i = np.eye(5)

In [53]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
i.shape

(5, 5)